=== Lab07/XML-Lab/Data/coursesDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This DTD is for describing the ACIT 4B schedule
-->

<!--
    TODO define vocabulary identification data
-->

<!ELEMENT data (day|course|time)*>


<!-- the highest repeating element is the day of the week, contains multiple time
elements to represent courses throughout the day  -->
<!ELEMENT day (time|booking)+>
<!ATTLIST day
    day (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!-- the time element must have a start and end attribute, and contains
elements that hold course information -->
<!ELEMENT time (booking|day)*>
<!ATTLIST time
    startTime (8:30|9:30|10:30|11:30|12:30|1:30|2:30|3:30|4:30) #REQUIRED
>

<!-- the course element contains many attributes that describe the course -->
<!ELEMENT booking ((course|time), room, instructor, type, endTime)>

<!ELEMENT course (#PCDATA|time|day)*>
<!ATTLIST course
    course CDATA #IMPLIED
>
<!ELEMENT room (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT endTime (#PCDATA)>

=== Lab07/XML-Lab/Data/courseData.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE data SYSTEM 'coursesDTD.dtd'>
<data>
    <!-- Monday -->
    <day day="Monday">
            <time startTime="1:30" endTime="3:20">
                    <course course="ACIT4770">
                            <room>SE12-306</room>
                            <instructor>Trevor Lord</instructor>
                            <type>Lecture</type>
                    </course>
            </time>
            <time startTime="3:30" endTime="4:20">
                    <course course="ACIT4910">
                            <room>SW9-206</room>
                            <instructor>Richard Chau</instructor>
                            <type>Lecture</type>
                    </course>
            </time>
            <time startTime="4:30" endTime="5:20">
                    <course course="ACIT4650">
                            <room>SE6-205</room>
                            <instructor>Medhat Elmasry</instructor>
                            <type>Lecture</type>
                    </course>
            </time>
    </day>
    <!-- Tuesday -->
    <day day="Tuesday">
            <time startTime="10:30" endTime="12:20">
                    <course course="ACIT4620">
                            <room>SE12-306</room>
                            <instructor>Bethany Edmunds</instructor>
                            <type>Lab</type>
                    </course>
            </time>
            <time startTime="12:30" endTime="1:20">
                    <course course="ACIT4650">
                            <room>SW9-206</room>
                            <instructor>Medhat Elmasry</instructor>
                            <type>Lecture</type>
                    </course>
            </time>
            <time startTime="1:30" endTime="3:20">
                    <course course="ACIT4650">
                            <room>SE12-306</room>
                            <instructor>Medhat Elmasry</instructor>
                            <type>Lab</type>
                    </course>
            </time>
            <time startTime="3:30" endTime="5:20">
                    <course course="ACIT4620">
                            <room>SW3-3615</room>
                            <instructor>Bethany Edmunds</instructor>
                            <type>Lecture</type>
                    </course>
            </time>
    </day>
    <!-- Wednesday -->
    <day day="Wednesday">
            <time startTime="10:30" endTime="12:20">
                    <course course="ACIT4660">
                            <room>SE12-306</room>
                            <instructor>Steve Fabiszewski</instructor>
                            <type>Lab</type>
                    </course>
            </time>
            <time startTime="12:30" endTime="2:20">
                    <course course="ACIT4850">
                            <room>SW3-1750</room>
                            <instructor>James Parry</instructor>
                            <type>Lecture</type>
                    </course>
            </time>
    </day>
    <!-- Thursday -->
    <day day="Thursday">
        <time startTime="9:30" endTime="10:20">
            <course course="ACIT4910">
                <room>SW5-1840</room>
                <instructor>Richard Chau</instructor>
                <type>Lecture</type>
            </course>
        </time>
        <time startTime="10:30" endTime="12:20">
            <course course="ACIT4850">
                <room>SE12-320</room>
                <instructor>James Parry</instructor>
                <type>Lab</type>
            </course>
        </time>
        <time startTime="1:30" endTime="3:20">
            <course course="ACIT4910">
                <room>SE12-306</room>
                <instructor>Richar Chau</instructor>
                <type>Lab</type>
            </course>
        </time>
    </day>
    <!-- Friday -->
    <day day="Friday">
        <time startTime="8:30" endTime="10:20">
            <course course="ACIT4660">
                <room>SW9-206</room>
                <instructor>Steve Fabiszewski</instructor>
                <type>Lecture</type>
            </course>
        </time>
    </day>
</data>

=== Lab07/XML-Lab/Data/byTimeData.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE data SYSTEM 'coursesDTD.dtd'>
<data>
<!-- 8:30 Classes -->
<time startTime="8:30">
	<day day="Friday">
            <booking>
		<course>ACIT4660</course>
			<room>SW9-206</room>
			<instructor>Steve Fabiszewski</instructor>
			<type>Lecture</type>
			<endTime>10:20</endTime>
            </booking>
	</day>
</time>
<!-- 9:30 Classes -->
<time startTime="9:30">
	<day day="Thursday">
            <booking>
		<course>ACIT4910</course>
			<room>SW5-1840</room>
			<instructor>Richard Chau</instructor>
			<type>Lecture</type>
			<endTime>10:20</endTime>
            </booking>
	</day>
	<day day="Friday">
            <booking>
		<course>ACIT4660</course>
			<room>SW9-206</room>
			<instructor>Steve Fabiszewski</instructor>
			<type>Lecture</type>
			<endTime>10:20</endTime>
            </booking>
	</day>
</time>
<!-- 10:30 Classes -->
<time startTime="10:30">
	<day day="Tuesday">
            <booking>
		<course>ACIT4620</course>
			<room>SE12-306</room>
			<instructor>Bethany Edmunds</instructor>
			<type>Lab</type>
			<endTime>12:20</endTime>
            </booking>
	</day>
	<day day="Wednesday">
            <booking>
		<course>ACIT4660</course>
			<room>SE12-306</room>
			<instructor>Steve Fabiszewski</instructor>
			<type>Lab</type>
			<endTime>12:20</endTime>
            </booking>
	</day>
	<day day="Thursday">
            <booking>
		<course>ACIT4850</course>
			<room>SE12-320</room>
			<instructor>James Parry</instructor>
			<type>Lab</type>
			<endTime>12:20</endTime>
            </booking>
	</day>
</time>
<!-- 11:30 Classes -->
<time startTime="11:30">
	<day day="Tuesday">
            <booking>
		<course>ACIT4620</course>
			<room>SE12-306</room>
			<instructor>Bethany Edmunds</instructor>
			<type>Lab</type>
			<endTime>12:20</endTime>
            </booking>
	</day>
	<day day="Wednesday">
            <booking>
		<course>ACIT4660</course>
			<room>SE12-306</room>
			<instructor>Steve Fabiszewski</instructor>
			<type>Lab</type>
			<endTime>12:20</endTime>
            </booking>
	</day>
	<day day="Thursday">
            <booking>
                <course>ACIT4850</course>
			<room>SE12-320</room>
			<instructor>James Parry</instructor>
			<type>Lab</type>
			<endTime>12:20</endTime>
            </booking>
	</day>
</time>
<!-- 12:30 Classes -->
<time startTime="12:30">
	<day day="Tuesday">
            <booking>
		<course>ACIT4650</course>
			<room>SW9-206</room>
			<instructor>Medhat Elmasry</instructor>
			<type>Lecture</type>
			<endTime>1:20</endTime>
            </booking>
	</day>
	<day day="Wednesday">
            <booking>
                <course>ACIT4850</course>
			<room>SW3-1750</room>
			<instructor>James Parry</instructor>
			<type>Lecture</type>
			<endTime>2:20</endTime>
            </booking>
	</day>
</time>
<!-- 1:30 Classes -->
<time startTime="1:30">
	<day day="Monday">
            <booking>
                <course>ACIT4770</course>
			<room>SE12-306</room>
			<instructor>Trevor Lord</instructor>
			<type>Lecture</type>
			<endTime>3:20</endTime>
            </booking>
	</day>
	<day day="Tuesday">
            <booking>
		<course>ACIT4650</course>
                <room>SE12-306</room>
                <instructor>Medhat Elmasry</instructor>
                <type>Lab</type>
                <endTime>3:20</endTime>
            </booking>
	</day>
	<day day="Wednesday">
            <booking>
                    <course>ACIT4850</course>
                    <room>SW3-1750</room>
                    <instructor>James Parry</instructor>
                    <type>Lecture</type>
                    <endTime>2:20</endTime>
            </booking>
	</day>
	<day day="Thursday">
            <booking>
		<course>ACIT4910</course>
                <room>SE12-306</room>
                <instructor>Richard Chau</instructor>
                <type>Lab</type>
                <endTime>3:20</endTime>
            </booking>
	</day>
</time>
<!-- 2:30 Classes -->
<time startTime="2:30">
	<day day="Monday">
            <booking>
		<course>ACIT4770</course>
                <room>SE12-306</room>
                <instructor>Trevor Lord</instructor>
                <type>Lecture</type>
                <endTime>3:20</endTime>
            </booking>
	</day>
	<day day="Tuesday">
            <booking>
		<course>ACIT4650</course>
                <room>SE12-306</room>
                <instructor>Medhat Elmasry</instructor>
                <type>Lab</type>
                <endTime>3:20</endTime>
            </booking>
	</day>
	<day day="Thursday">
            <booking>
		<course>ACIT4910</course>
                <room>SE12-306</room>
                <instructor>Richard Chau</instructor>
                <type>Lab</type>
                <endTime>3:20</endTime>
            </booking>
	</day>
</time>
<!-- 3:30 Classes -->
<time startTime="3:30">
	<day day="Monday">
            <booking>
                <course>ACIT4910</course>
                <room>SW9-206</room>
                <instructor>Richard Chau</instructor>
                <type>Lecture</type>
                <endTime>4:20</endTime>
            </booking>
	</day>
	<day day="Tuesday">
            <booking>
		<course>ACIT4620</course>
                <room>SW3-3615</room>
                <instructor>Bethany Edmunds</instructor>
                <type>Lecture</type>
                <endTime>5:20</endTime>
            </booking>
	</day>
</time>
<!-- 4:30 Classes -->
<time startTime="4:30">
	<day day="Monday">
            <booking>
                <course>ACIT4650</course>
                <room>SE6-205</room>
                <instructor>Medhat Elmasry</instructor>
                <type>Lecture</type>
                <endTime>5:20</endTime>
            </booking>
	</day>
	<day day="Tuesday">
            <booking>
                <course>ACIT4620</course>
                <room>SW3-3615</room>
                <instructor>Bethany Edmunds</instructor>
                <type>Lecture</type>
                <endTime>5:20</endTime>
            </booking>
	</day>
</time>
</data>

=== Lab07/XML-Lab/Data/byCourseData.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE data SYSTEM 'coursesDTD.dtd'>
<data>
<!-- ACIT4770 -->
<course course="ACIT4770">
	<day day="Monday">
            <booking>
		<time startTime="1:30"></time>
			<room>SE12-306</room>
			<instructor>Trevor Lord</instructor>
			<type>Lecture</type>
                        <endTime>3:20</endTime>
            </booking>
	</day>
</course>
<!-- ACIT4910 -->
<course course="ACIT4910">
	<day day="Monday">
            <booking>
		<time startTime="3:30"></time>
			<room>SW9-206</room>
			<instructor>Richard Chau</instructor>
			<type>Lecture</type>
                        <endTime>4:20</endTime>
            </booking>
	</day>
	<day day="Thursday">
            <booking>
		<time startTime="9:30"></time>
			<room>SW5-1840</room>
			<instructor>Richard Chau</instructor>
			<type>Lecture</type>
                        <endTime>10:20</endTime>
            </booking>
                <booking>
		<time startTime="1:30"></time>
			<room>SW5-1840</room>
			<instructor>Richard Chau</instructor>
			<type>Lab</type>
                        <endTime>3:20</endTime>
                </booking>
	</day>
</course>
<!-- ACIT4650 -->
<course course="ACIT4650">
	<day day="Monday">
            <booking>
		<time startTime="4:30"></time>
			<room>SE6-205</room>
			<instructor>Medhat Elmasry</instructor>
			<type>Lecture</type>
                        <endTime>5:20</endTime>
            </booking>
	</day>
	<day day="Tuesday">
            <booking>
		<time startTime="12:30"></time>
			<room>SW9-206</room>
			<instructor>Medhat Elmasry</instructor>
			<type>Lecture</type>
                        <endTime>1:20</endTime>
            </booking>
            <booking>
		<time startTime="1:30"></time>
			<room>SE12-306</room>
			<instructor>Medhat Elmasry</instructor>
			<type>Lab</type>
                        <endTime>3:20</endTime>

            </booking>
	</day>
</course>
<!-- ACIT4620-->
<course>
    <day day="Tuesday">
        <booking>
        <time startTime="10:30"></time>
                <room>SE12-306</room>
                <instructor>Bethany Edmunds</instructor>
                <type>Lab</type>
                <endTime>12:20</endTime>
        </booking>
        <booking>
        <time startTime="3:30"></time>
                <room>SW3-3615</room>
                <instructor>Bethany Edmunds</instructor>
                <type>Lecture</type>
                <endTime>5:20</endTime>
        </booking>
    </day>
</course>
<!-- ACIT4660-->
<course>
    <day day="Wednesday">
        <booking>
        <time startTime="10:30"></time>
                    <room>SE12-306</room>
                    <instructor>Steve Fabiszewski</instructor>
                    <type>Lab</type>
                    <endTime>12:20</endTime>
        </booking>
    </day>
    <day day="Friday">
        <booking>
        <time startTime="8:30"></time>
                    <room>SW9-206</room>
                    <instructor>Steve Fabiszewski</instructor>
                    <type>Lecture</type>
                    <endTime>10:20</endTime>
        </booking>
    </day>
</course>
<!-- ACIT4850-->
<course>
    <day day="Wednesday">
        <booking>
        <time startTime="12:30"></time>
                    <room>SW3-1750</room>
                    <instructor>James Parry</instructor>
                    <type>Lecture</type>
                    <endTime>2:20</endTime>
        </booking>
        
    </day>
    <day day="Friday">
        <booking>
        <time startTime="10:30"></time>
                    <room>SE12-320</room>
                    <instructor>James Parry</instructor>
                    <type>Lab</type>
                    <endTime>12:20</endTime>
        </booking>
    </day>
</course>
</data>
